name: htr_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - torch
      - torchvision
      - pyyaml
      - pytesseract
      - datasets
      - python-Levenshtein
      - pillow
      - transformers
      - peft
      - pandas
      - matplotlib
      - boto3
      - google-cloud-storage # for the client to handle artifact upload in bucket
      - python-dotenv
      - onnxruntime
      - onnx
      - tensorboard