name: htr_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - tesseract
  - pillow
  - python-Levenshtein
  - pip:
      - mlflow
      - torch
      - torchvision
      - pyyaml
      - pytesseract
