name: htr_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - torch
      - torchvision
      - pyyaml
      - pytesseract
      - datasets
      - python-Levenshtein
      - pillow
      - transformers
      - pandas
      - boto3
      - python-dotenv
      - onnxruntime
      - onnx