problem_type: Transcription
experiment_name: HTR - Baselines
run_name: tesseract_iam_line_test
granularity: line
dataset: Teklia/IAM-line
model: Tesseract
pipeline: line_to_text
data_path: Teklia/IAM-line
fine_tuning:
  enabled: false
params:
  tesseract_language: eng
  tesseract_engine_mode: 3
