experiment_name: "Hector dataset test - TrOCR FR LoRA"
run_name: "TrOCR-FR LoRA (local adapters) - hector_pages_lines_3_test"
pipeline: "line_to_text"
dataset:
  name: "local_lines"
  images_dir: "data_local/perso_dataset/hector_pages_lines_3_test/lines_out_sorted"
  ground_truth_path: "data_local/perso_dataset/hector_pages_lines_3_test/gt_hector_test.json"
model: "trocr_fr_finetuned"
preprocessor:
  - name: "binarize"

