experiment_name: "Hector dataset measures"
run_name: "TrOCR-FR on Hector dataset"
pipeline: "line_to_text"
dataset: "local_lines"
model: "trocr_fr"
preprocessor: 
  - name: "resize"
    height: 128
  - name: "binarize"

