experiment_name: "Hector dataset good resolution measures"
run_name: "CRNN-F measures"
pipeline: "line_to_text"
dataset: "local_lines"
model: "crnn_f"
preprocessor: 
  - name: "resize"
    height: 128
  - name: "binarize"

