experiment_name: "TrOCR Inference Test"
run_name: "TrOCR-fr on IAM-line"
pipeline: "line_to_text"
dataset: 
  name: "teklia/iam-line"
#  lines_dir: "data_local/perso_dataset/fatima_full_1100_lines/dataset_train_val/lines"
#  ground_truth_txt_path: "data_local/perso_dataset/fatima_full_1100_lines/dataset_train_val/gt_train_val.txt"
#  display_name: "fatima_1100_lines"
model:
  name: "trocr_fr"
preprocessor: 
    - name: "identity"


