experiment_name: "TrOCR vs TrOCR-FR test"
run_name: "TrOCR - FR on 515 lines perso"
pipeline: "line_to_text"
dataset: 
  name: "local_lines"
  images_dir: "data_local/perso_dataset/hector_200_more_lines_extended/lines_out_sorted"
  ground_truth_path: "data_local/perso_dataset/hector_200_more_lines_extended/gt_hector_pages_lines.json"
model:
  name: "trocr_fr"
preprocessor: 
    - name: "identity"


