experiment_name: "Model Performance Time Tests"
run_name: "Qwen-3B on Fatima dataset"
pipeline: "line_to_text"
dataset: 
  name: "local_lines_text"
  lines_dir: "data_local/perso_dataset/fatima_full_1100_lines/dataset_train_val/lines"
  ground_truth_txt_path: "data_local/perso_dataset/fatima_full_1100_lines/dataset_train_val/gt_train_val.txt"
  display_name: "fatima_1100_lines"
model:
  name: "qwen_vl"
  pretrained_model_name: "Qwen/Qwen2.5-VL-3B-Instruct"
  device_map: "auto"
  torch_dtype: "auto"
  max_new_tokens: 256
  prompt: "Read and transcribe all text in the image exactly. Output only the transcription."
preprocessor: 
  - "identity"
