experiment_name: "Measures of TrOCR finetuning only"
run_name: "TrOCR-FR finetuned naive larger dataset"
pipeline: "line_to_text"
dataset:
  name: "local_lines"
  images_dir: "data_local/perso_dataset/hector_pages_lines_3_test_2/lines_out_sorted"
  ground_truth_path: "data_local/perso_dataset/hector_pages_lines_3_test_2/gt_hector_test.json"
model: "trocr_fr_finetuned"
preprocessor:
  - name: "identity"
