experiment_name: "CRNNs and image preprocess"
run_name: "trocr-local-test-with-preprocessing"
pipeline: "line_to_text"
dataset: "local_lines"
model: "trocr"
preprocessor:
  name: "resize"
  height: 64
