experiment_name: "Measures of TrOCR finetuning only"
run_name: "TrOCR-FR finetuned model logged on mlflow"
pipeline: "line_to_text"
dataset:
  name: "local_lines"
  images_dir: "data_local/perso_dataset/hector_pages_lines_3_test_2/lines_out_sorted"
  ground_truth_path: "data_local/perso_dataset/hector_pages_lines_3_test_2/gt_hector_test.json"
model:
  name: "trocr_fr_finetuned"
  mlflow_run_id: "d9757bc67c1b48028849bfd336a00e19"
preprocessor:
  - name: "identity"
