experiment_name: "Checking TrOCR on IAM-line"
run_name: "trocr_base_handwritten_iam_line"

pipeline: "line_to_text"

dataset: "teklia/iam-line"

preprocessor:
  - "identity"

model:
  name: "trocr"
  max_new_tokens: 256